# .github/slsa/.slsa-goreleaser.yml  (or at repo root as .slsa-goreleaser.yml)
version: 1

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath

# Build matrix
goos:
  - linux
  - windows
  - darwin
goarch:
  - amd64
  - arm64

# 👉 Set this to the folder that contains your main.go
# Examples:
#   main: ./cmd/tesmart-ui          # if your main.go is in cmd/tesmart-ui/main.go
#   main: ./cmd/server
#   main: .                         # if main.go is at repo root
main: ./cmd/tesmart-ui

# Name pattern for output binary
binary: tesmart-ui-{{ .Os }}-{{ .Arch }}
